# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: WeeWX
version: "0.0.1"
slug: weewx
description: WeeWX for Home Assistant
url: "https://github.com/msandy/home-assistant-addons/tree/main/weewx"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/msandy/{arch}-addon-weewx"
